---
- name: Ensure Flux CLI unpack directory exists
  ansible.builtin.file:
    path: "{{ flux_cli_unpack_directory }}"
    state: directory
    mode: "0755"

- name: Download and extract Flux CLI archive
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ flux_cli_archive_url }}"
    dest: "{{ flux_cli_unpack_directory }}"

- name: Ensure Flux CLI binary directory exists
  ansible.builtin.file:
    path: "{{ flux_cli_bin_directory }}"
    state: directory
    mode: "0755"

- name: Copy Flux CLI executable to binary directory
  ansible.builtin.copy:
    remote_src: true
    src: "{{ (flux_cli_unpack_directory, 'flux') | path_join }}"
    dest: "{{ flux_cli_bin_directory }}"
    mode: "0755"

- name: Ensure Flux CLI shell completions are in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: source <(flux completion bash)
