---
- name: Ensure unpack directory exists
  ansible.builtin.file:
    path: "{{ k9s_unpack_directory }}"
    state: directory
    mode: "0755"

- name: Download and extract K9s archive
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ k9s_archive_url }}"
    dest: "{{ k9s_unpack_directory }}"

- name: Ensure binary directory exists
  ansible.builtin.file:
    path: "{{ k9s_bin_directory }}"
    state: directory
    mode: "0755"

- name: Copy executable to binary directory
  ansible.builtin.copy:
    remote_src: true
    src: "{{ (k9s_unpack_directory, 'k9s') | path_join }}"
    dest: "{{ k9s_bin_directory }}"
    mode: "0755"

- name: Ensure K9s shell completions are in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: source <(k9s completion bash)
