---

- name: Get Consul service information
  command: >-
    kubectl get service
      --namespace {{ consul_release_namespace }}
      --selector {{ consul_server_service_selector }}
      --output json
  register: consul_services_cmd
  vars:
    consul_server_service_selector: "app={{ consul_release_name }},component=server"

- name: Set Consul server services fact
  set_fact:
    consul_server_services: "{{ (consul_services_cmd.stdout | from_json)['items'] }}"

- name: Set Consul server facts
  set_fact:
    consul_server_host: >-
      {{-
        consul_server_host
        if consul_server_host is defined
        else (
          "{}.{}".format(
            consul_server_service.metadata.name,
            consul_server_service.metadata.namespace
          )
        )
      }}
    consul_server_port: >-
      {{-
        consul_server_port
        if consul_server_port is defined
        else (
          consul_server_service.spec.ports |
            selectattr('name', 'equalto', 'http') |
            map(attribute = 'port') |
            first
        )
      }}
  vars:
    consul_server_service: "{{ consul_server_services | first }}"
  when: consul_server_services | length > 0
