---
# Try to obtain a Keycloak admin token with the password from the config
- name: Get Keycloak admin token
  # checkov:skip=CKV2_ANSIBLE_1: TLS is optional
  # checkov:skip=CKV_ANSIBLE_1: Certificate validation is optional
  ansible.builtin.uri:
    url: "{{ keycloak_base_url }}/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: password
      client_id: admin-cli
      username: "{{ keycloak_admin_username }}"
      password: "{{ keycloak_admin_password }}"
    # An authentication error (401) is an expected status code here until <26.6.0
    # then 400: https://github.com/keycloak/keycloak/pull/46528
    status_code:
      - 200
      - 400
      - 401
    ca_path: "{{ keycloak_ca_path }}"
    validate_certs: "{{ keycloak_validate_certs }}"
  register: keycloak_admin_token_req
  # This is the first task that tries to access the Keycloak API, so retry when there
  # is an SSL error (reported as -1) as cert-manager takes time to create certs
  # We also retry when the service is not available
  retries: 60
  delay: 10
  until: keycloak_admin_token_req.status not in [-1, 503]

- name: Set Keycloak admin token fact
  ansible.builtin.set_fact:
    keycloak_admin_token: "{{ keycloak_admin_token_req.json.access_token }}"
  when: keycloak_admin_token_req.status == 200

- name: Configure SSL requirement for master realm
  ansible.builtin.uri:
    # checkov:skip=CKV2_ANSIBLE_1: TLS is optional
    # checkov:skip=CKV_ANSIBLE_1: Certificate validation is optional
    url: "{{ keycloak_base_url }}/admin/realms/master"
    method: PUT
    headers:
      authorization: "Bearer {{ keycloak_admin_token }}"
    body_format: json
    body:
      sslRequired: "{{ 'external' if ingress_tls_enabled else 'none' }}"
    ca_path: "{{ keycloak_ca_path }}"
    validate_certs: "{{ keycloak_validate_certs }}"
    status_code:
      - 204

- name: Set facts for crossplane
  ansible.builtin.set_fact:
    keycloak_base_url: "{{ keycloak_base_url }}"
    keycloak_admin_password: "{{ keycloak_admin_password }}"
