---
- name: Ensure unpack directory exists
  ansible.builtin.file:
    path: "{{ helm_unpack_directory }}"
    state: directory
    mode: "0755"

- name: Download and extract Helm archive
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ helm_archive_url }}"
    dest: "{{ helm_unpack_directory }}"

- name: Ensure binary directory exists
  ansible.builtin.file:
    path: "{{ helm_bin_directory }}"
    state: directory
    mode: "0755"

- name: Copy executable to binary directory
  ansible.builtin.copy:
    remote_src: true
    src: "{{ (helm_unpack_directory, helm_archive_subdirectory, 'helm') | path_join }}"
    dest: "{{ helm_bin_directory }}"
    mode: "0755"

- name: Ensure Helm shell completions are in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: source <(helm completion bash)
