---
namespace: azimuth_cloud
name: azimuth_ops
version: 0.1.0
description: Roles and playbooks for performing Azimuth operations.
readme: README.md
authors:
  - "Matt Pryor <matt@stackhpc.com>"
license:
  - "Apache-2.0"
repository: "https://github.com/azimuth-cloud/ansible-collection-azimuth-ops"

dependencies:
  ansible.posix: "1.6.1"
  community.general: "7.4.0"
  kubernetes.core: "5.0.0"
  "git+https://github.com/azimuth-cloud/ansible-collection-terraform.git": "0.4.0"
