---
namespace: azimuth_cloud
name: azimuth_ops
version: 0.1.0
description: Roles and playbooks for performing Azimuth operations.
readme: README.md
authors:
  - "Matt Pryor <matt@stackhpc.com>"
license:
  - "Apache-2.0"
repository: "https://github.com/azimuth-cloud/ansible-collection-azimuth-ops"

dependencies:
  ansible.posix: "2.0.0"
  community.general: "10.6.0"
  kubernetes.core: "5.1.0"
  "git+https://github.com/azimuth-cloud/ansible-collection-terraform.git": "0.6.0"
