---

- name: Fetch services from Consul
  command: >-
    kubectl exec {{ zenith_migrate_consul_release_name }}-server-0
      --namespace {{ zenith_migrate_consul_release_namespace }}
      --
      consul kv get -keys zenith/subdomains/
  vars:
    zenith_migrate_consul_release_name: "{{ consul_release_name | default('consul') }}"
    zenith_migrate_consul_release_namespace: >-
      {{
        consul_release_namespace |
          default(azimuth_release_namespace) |
          default('azimuth')
      }}
  register: zenith_migrate_consul_services_cmd

- name: Create service CRDs
  include_tasks: migrate-create-service.yml
  loop: >-
    {{
      zenith_migrate_consul_services_cmd.stdout_lines |
        map("regex_replace", "^zenith/subdomains/", "")
    }}
  loop_control:
    loop_var: zenith_migrate_service_name
