---
- name: Make kustomization directory
  ansible.builtin.file:
    path: "{{ clusterapi_kustomization_directory }}"
    state: directory
    mode: "0755"

- name: Write kustomization file
  ansible.builtin.copy:
    content: "{{ clusterapi_kustomization | to_nice_yaml }}"
    dest: "{{ clusterapi_kustomization_directory }}/kustomization.yaml"
    mode: "0644"

- name: Install Cluster API resources
  ansible.builtin.command: kubectl apply -k {{ clusterapi_kustomization_directory }}
  register: kubectl_clusterapi_resources
  changed_when: kubectl_clusterapi_resources.stdout_lines | select('match', '(?!.*unchanged$)') | length > 0

- name: Remove legacy CAPO mutating webhook
  ansible.builtin.command: kubectl delete mutatingwebhookconfiguration capo-mutating-webhook-configuration
  register: clusterapi_capo_mutating_webhook_delete
  changed_when: clusterapi_capo_mutating_webhook_delete.rc == 0
  failed_when: >-
    clusterapi_capo_mutating_webhook_delete.rc != 0 and
    "NotFound" not in clusterapi_capo_mutating_webhook_delete.stderr

- name: Wait for Cluster API controllers to become ready
  ansible.builtin.command: >-
    kubectl rollout status
      --namespace {{ watch.namespace }}
      --timeout 1s
      {{ watch.kind }}/{{ watch.name }}
  changed_when: false
  register: clusterapi_controller_wait
  until: clusterapi_controller_wait is succeeded
  retries: 60
  delay: 10
  loop: "{{ clusterapi_watches }}"
  loop_control:
    loop_var: watch
    label: "{{ watch.namespace }}/{{ watch.kind }}/{{ watch.name }}"

- name: Install Cluster API addon provider
  kubernetes.core.helm:
    chart_ref: "{{ clusterapi_addon_provider_chart_name }}"
    chart_repo_url: "{{ clusterapi_addon_provider_chart_repo }}"
    chart_version: "{{ clusterapi_addon_provider_chart_version }}"
    release_namespace: "{{ clusterapi_addon_provider_release_namespace }}"
    release_name: "{{ clusterapi_addon_provider_release_name }}"
    release_values: "{{ clusterapi_addon_provider_release_values }}"
    atomic: true
    create_namespace: true
    wait: true
    wait_timeout: "{{ clusterapi_addon_provider_wait_timeout }}"

- name: Install Cluster API janitor
  kubernetes.core.helm:
    chart_ref: "{{ clusterapi_janitor_openstack_chart_name }}"
    chart_repo_url: "{{ clusterapi_janitor_openstack_chart_repo }}"
    chart_version: "{{ clusterapi_janitor_openstack_chart_version }}"
    release_namespace: "{{ clusterapi_janitor_openstack_release_namespace }}"
    release_name: "{{ clusterapi_janitor_openstack_release_name }}"
    release_values: "{{ clusterapi_janitor_openstack_release_values }}"
    atomic: true
    create_namespace: true
    wait: true
    wait_timeout: "{{ clusterapi_janitor_openstack_wait_timeout }}"
