---

# Indicates whether TLS should be enabled
keycloak_ingress_tls_enabled: "{{ ingress_tls_enabled | default(True) }}"

# The Keycloak admin username
keycloak_admin_username: admin
# The Keycloak admin password
keycloak_admin_password: "{{ undef(hint='keycloak_admin_password is not defined') }}"

# The name of the secret containing the initial admin password
keycloak_initial_admin_secret_name: "keycloak_initial-admin"
# The bootstrap admin username
keycloak_bootstrap_admin_username: "temp-admin"

# The base URL of Keycloak
keycloak_base_url: >-
  {{-
    "{}://identity.{}".format(
      'https' if keycloak_ingress_tls_enabled else 'http',
      ingress_base_domain
    )
  }}
keycloak_ca_path: /etc/ssl/certs/ca-certificates.crt

# Whether or not to validate SSL certificates when talking to the Keycloak API
keycloak_validate_certs: true
