---

- name: Check if AWX CRD exists
  command: kubectl get crd awxs.awx.ansible.com
  register: awx_get_crd
  changed_when: false
  failed_when: >-
    awx_get_crd.rc != 0 and
    "NotFound" not in awx_get_crd.stderr

# We only remove AWX components if the awx_purge flag is set
# If it is not set, we just don't touch AWX
# In either case, Azimuth itself will be reconfigured to use the CRD

- name: Remove AWX components
  block:
    - name: Remove AWX instance
      command: >-
        kubectl delete awx {{ awx_name }} --namespace {{ awx_namespace }}
      register: awx_delete_instance
      changed_when: "awx_delete_instance.rc == 0"
      failed_when: >-
        awx_delete_instance.rc != 0 and
        "NotFound" not in awx_delete_instance.stderr

    - name: Remove AWX database configuration
      command: >-
        kubectl delete secret {{ awx_postgresql_configuration_secret_name }} --namespace {{ awx_namespace }}
      register: awx_delete_db_config_secret
      changed_when: "awx_delete_db_config_secret.rc == 0"
      failed_when: >-
        awx_delete_db_config_secret.rc != 0 and
        "NotFound" not in awx_delete_db_config_secret.stderr

    - name: Remove AWX trust bundle
      command: >-
        kubectl delete secret {{ awx_trust_bundle_secret_name }} --namespace {{ awx_namespace }}
      register: awx_delete_trust_bundle
      changed_when: "awx_delete_trust_bundle.rc == 0"
      failed_when: >-
        awx_delete_trust_bundle.rc != 0 and
        "NotFound" not in awx_delete_trust_bundle.stderr

    - name: Set AWX admin password secret fact
      set_fact:
        awx_admin_password_secret_name: "{{ awx_name }}-admin-password"
      when: awx_admin_password_secret_name is not defined

    - name: Remove AWX admin password secret
      command: >-
        kubectl delete secret {{ awx_admin_password_secret_name }} --namespace {{ awx_namespace }}
      register: awx_delete_admin_password_secret
      changed_when: "awx_delete_admin_password_secret.rc == 0"
      failed_when: >-
        awx_delete_admin_password_secret.rc != 0 and
        "NotFound" not in awx_delete_admin_password_secret.stderr

    - name: Remove AWX postgresql instance
      kubernetes.core.helm:
        release_namespace: "{{ awx_namespace }}"
        release_name: "{{ awx_postgresql_release_name }}"
        state: absent
        wait: yes

    - name: Remove postgresql auth secret
      command: >-
        kubectl delete secret {{ awx_postgresql_auth_secret_name }} --namespace {{ awx_namespace }}
      register: awx_delete_postgresql_auth_secret
      changed_when: "awx_delete_postgresql_auth_secret.rc == 0"
      failed_when: >-
        awx_delete_postgresql_auth_secret.rc != 0 and
        "NotFound" not in awx_delete_postgresql_auth_secret.stderr

    - name: Create directory to contain kustomize overlay
      file:
        path: "{{ awx_operator_directory }}/config/remove-ns"
        state: directory

    - name: Add kustomize overlay files to remove namespace from output
      template:
        src: "{{ item }}"
        dest: "{{ awx_operator_directory }}/config/remove-ns/{{ item }}"
      loop:
        - kustomization.yaml
        - patch-delete-ns.yaml

    - name: Remove AWX operator
      command: kubectl delete -k {{ awx_operator_directory }}/config/remove-ns

    - name: Delete AWX operator clone
      file:
        path: "{{ awx_operator_directory }}"
        state: absent

  when:
    # There is only anything to do if the CRD exists
    - "awx_get_crd.rc == 0"
    - "awx_purge | default(False)"
