azimuth_authorization_webhook_chart_name: azimuth-authorization-webhook
azimuth_authorization_webhook_chart_repo: https://azimuth-cloud.github.io/azimuth-authorization-webhook
azimuth_authorization_webhook_chart_version: 0.1.0-dev.0.feat-system-users.49
azimuth_authorization_webhook_release_namespace: azimuth
azimuth_authorization_webhook_release_name: azimuth-authorization-webhook

azimuth_authorization_webhook_ingress_class_name: nginx
azimuth_authorization_webhook_tls_enabled: true
azimuth_authorization_webhook_tls_secret_name: azimuth-authorization-webhook-tls

azimuth_authorization_webhook_ingress_subdomain: authorization
azimuth_authorization_webhook_host: >-
  {{-
    "{}.{}".format(azimuth_authorization_webhook_ingress_subdomain, ingress_base_domain)
    if azimuth_authorization_webhook_ingress_subdomain is defined and ingress_base_domain is defined
    else undef(hint = 'azimuth_authorization_webhook_host is required')
  }}

azimuth_authorization_webhook_protected_namespaces:
  - kube-system
  - openstack-system
  - tigera-operator
  - calico-system
  - calico-apiserver
  - csi-ceph-system
  - ingress-nginx
  - monitoring-system
  - node-feature-discovery
  - gpu-operator
  - intel
  - cert-manager
  - network-operator
  - node-problem-detector

azimuth_authorization_webhook_release_defaults:
  protectedNamespaces: "{{ azimuth_authorization_webhook_protected_namespaces }}"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    ingressClassName: "{{ azimuth_authorization_webhook_ingress_class_name }}"
    host: "{{ azimuth_authorization_webhook_host }}"
    tls:
      enabled: "{{ azimuth_authorization_webhook_tls_enabled }}"
      secretName: "{{ azimuth_authorization_webhook_tls_secret_name }}"

azimuth_authorization_webhook_release_overrides: {}
azimuth_authorization_webhook_release_values: >-
  {{-
    azimuth_authorization_webhook_release_defaults |
      combine(azimuth_authorization_webhook_release_overrides, recursive = True)
  }}
azimuth_authorization_webhook_wait_timeout: 2m
