---
- name: Install NGINX Ingress Controller on target Kubernetes cluster
  kubernetes.core.helm:
    chart_ref: "{{ ingress_nginx_chart_name }}"
    chart_repo_url: "{{ ingress_nginx_chart_repo }}"
    chart_version: "{{ ingress_nginx_chart_version }}"
    release_namespace: "{{ ingress_nginx_release_namespace }}"
    release_name: "{{ ingress_nginx_release_name }}"
    release_values: "{{ ingress_nginx_release_values }}"
    atomic: true
    create_namespace: true
    wait: true
    wait_timeout: "{{ ingress_nginx_wait_timeout }}"

- name: Configure custom alerting rules for certificate expiry
  ansible.builtin.command: kubectl apply -f -
  args:
    stdin: "{{ nginx_ingress_alert_rules_definition | to_nice_yaml }}"
  vars:
    nginx_ingress_alert_rules_definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: nginx-ingress-alerting-rules
        namespace: "{{ ingress_nginx_release_namespace }}"
        labels:
          release: kube-prometheus-stack
      spec:
        groups:
          - name: ingress_nginx.rules
            rules:
              - alert: NginxIngressCertificateExpiresSoon
                expr: |
                  nginx_ingress_controller_ssl_expire_time_seconds < (time() + (30 * 24 * 3600))
                for: 1h
                annotations:
                  message: "{% raw %}The cert {{ $labels.name }} is {{ $value | humanizeDuration }} from expiry.{% endraw %}"
                labels:
                  severity: warning
              - alert: NginxIngressCertificateExpiresVerySoon
                expr: |
                  nginx_ingress_controller_ssl_expire_time_seconds < (time() + (7 * 24 * 3600))
                for: 1m
                annotations:
                  message: "{% raw %}The cert {{ $labels.name }} is {{ $value | humanizeDuration }} from expiry.{% endraw %}"
                labels:
                  severity: critical
  register: kubectl_ingress_cert_expiry
  changed_when: kubectl_ingress_cert_expiry.stdout_lines | select('match', '(?!.*unchanged$)') | length > 0
  when: ingress_nginx_prometheus_stack_enabled
