
- name: Ensure Velero components are installed
  include_tasks: install.yml

- name: Apply backup schedule
  ansible.builtin.command: kubectl apply -f -
  args:
    stdin: "{{ velero_schedule_definition | to_nice_yaml }}"
  vars:
    velero_schedule_definition:
      apiVersion: velero.io/v1
      kind: Schedule
      metadata:
        name: "{{ velero_backup_schedule_name }}"
        namespace: "{{ velero_release_namespace }}"
      spec: "{{ velero_backup_schedule_spec }}"
