---
- name: Ensure bin directory exists
  ansible.builtin.file:
    path: "{{ kustomize_bin_directory }}"
    state: directory
    mode: "0755"

- name: Download and extract kustomize binary
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ kustomize_archive_url }}"
    dest: "{{ kustomize_bin_directory }}"
