---
- name: Ensure bin directory exists
  ansible.builtin.file:
    path: "{{ kubectl_bin_directory }}"
    state: directory
    mode: "0755"

- name: Download and install kubectl binary
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ (kubectl_bin_directory, 'kubectl') | path_join }}"
    mode: "0755"
    force: true

- name: Ensure kubectl shell completions are in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: source <(kubectl completion bash)
