---

# The timeout to wait for Harbor to become ready
harbor_wait_timeout: 10m

# The scheme for the Harbor external URL
harbor_external_url_scheme: "{{ 'https' if ingress_tls_enabled else 'http' }}"
# The external URL for Harbor
harbor_external_url: "{{ harbor_external_url_scheme }}://registry.{{ ingress_base_domain }}"

# Override this with site config
harbor_admin_password: "{{ undef(hint='harbor_admin_password is required') }}"

# Settings for persistence
harbor_persistence_pvc_registry_size: 5Gi

harbor_proxy_cache_set_quotas: true
# Global default size for proxy cache projects, can be overridden per-project. Defaults
# to 80% of registry volume size, split evenly between projects
harbor_default_proxy_cache_quota: >-
  {{ ( harbor_persistence_pvc_registry_size | replace('i','B') | human_to_bytes * 0.8 / (harbor_proxy_cache_projects.keys() | length)) | int }}

# Path to a CA file to use when talking to the Harbor API
harbor_ca_path: /etc/ssl/certs/ca-certificates.crt
# Whether or not to validate SSL certificates when talking to the Harbor API
harbor_validate_certs: true

# The proxy cache projects to create
harbor_proxy_cache_projects: {}
  # docker.io:
  #   name: dockerhub-public
  #   type: docker-hub
  #   url: https://hub.docker.com
  #   quota: "{{ harbor_default_proxy_cache_quota }}"
