---
- name: Find the block device for the k3s storage volume
  block:
    - name: Stat candidate device paths
      ansible.builtin.stat:
        path: "/dev/disk/by-id/{{ item }}"
      loop:
        # KVM
        - "{{ 'virtio-{}'.format(k3s_storage_volume_id[:20]) }}"
        # KVM #852
        - "{{ 'virtio-{}'.format(k3s_storage_volume_id) }}"
        # KVM virtio-scsi
        - "{{ 'scsi-0QEMU_QEMU_HARDDISK_{}'.format(k3s_storage_volume_id[:20]) }}"
        # KVM virtio-scsi #852
        - "{{ 'scsi-0QEMU_QEMU_HARDDISK_{}'.format(k3s_storage_volume_id) }}"
        # ESXi
        - "{{ 'wwn-0x{}'.format(k3s_storage_volume_id | replace('-', '')) }}"
      register: candidate_device_paths_stat

    - name: Set volume block device name
      ansible.builtin.set_fact:
        k3s_storage_device: >-
          /dev/{{
            candidate_device_paths_stat.results |
              selectattr("stat.exists") |
              map(attribute = "stat.lnk_source") |
              first |
              default("") |
              trim("/") |
              split("/") |
              last
          }}

    - name: Fail if block device was not found
      ansible.builtin.fail:
        msg: "Could not locate block device for volume {{ k3s_storage_volume_id }}."
      when: k3s_storage_device == "/dev/"


- name: Ensure filesystem exists on storage device
  community.general.filesystem:
    fstype: "{{ k3s_storage_fstype }}"
    dev: "{{ k3s_storage_device }}"

- name: Mount filesystem at required location
  ansible.posix.mount:
    src: "{{ k3s_storage_device }}"
    fstype: "{{ k3s_storage_fstype }}"
    path: /var/lib/rancher/k3s
    state: mounted

# XFS requires the filesystem to be mounted to do this
- name: Grow filesystem to fill available space
  community.general.filesystem:
    fstype: "{{ k3s_storage_fstype }}"
    dev: "{{ k3s_storage_device }}"
    resizefs: true

- name: Download k3s binary
  ansible.builtin.get_url:
    url: "{{ k3s_binary_url }}"
    checksum: "{{ k3s_binary_checksum }}"
    dest: /usr/bin/k3s
    mode: u=rwx,g=rx,o=rx
  register: k3s_binary

- name: Install k3s server systemd unit file
  ansible.builtin.template:
    src: k3s-server.service.j2
    dest: /etc/systemd/system/k3s-server.service
    owner: root
    group: root
    mode: "0644"
  register: k3s_server_systemd_unit

- name: Reload systemd units # noqa no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: k3s_server_systemd_unit is changed

- name: Ensure k3s server is started
  ansible.builtin.service:
    name: k3s-server
    state: >-
      {{-
        'restarted'
        if k3s_binary is changed or k3s_server_systemd_unit is changed
        else 'started'
      }}
    enabled: true
