{
 "title": "Consul",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Server Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Election events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(consul_raft_state_candidate{job=\"consul-server\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Raft commits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(consul_raft_apply{job=\"consul-server\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(increase(consul_runtime_gc_pause_ns_sum{job=\"consul-server\"}[1m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average raft commit time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(consul_raft_commitTime_sum{job=\"consul-server\"}[1m]) / increase(consul_raft_commitTime_count{job=\"consul-server\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Client Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RPC requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(consul_client_rpc{job=~\".*consul-client\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPC failure rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(increase(consul_client_rpc_failed{job=~\".*consul-client\"}[1m])) by(pod)) / (sum(increase(consul_client_rpc{job=~\".*consul-client\"}[1m])) by(pod)) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KV Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "KV  applies",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(consul_kvs_apply_count{job=\"consul-server\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average KV apply time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(consul_kvs_apply_sum{job=\"consul-server\"}[1m]) / increase(consul_kvs_apply_count{job=\"consul-server\"}[1m])) by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average transaction apply time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(consul_txn_apply_sum{job=\"consul-server\"}[1m]) / increase(consul_txn_apply_count{job=\"consul-server\"}[1m])) by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Service Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Catalog operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(consul_catalog_register_count{job=\"consul-server\"}[1m]) + increase(consul_catalog_deregister_count{job=\"consul-server\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average catalog operation time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum((increase(consul_catalog_register_sum{job=\"consul-server\"}[1m]) + increase(consul_catalog_deregister_sum{job=\"consul-server\"}[1m])) / (increase(consul_catalog_register_count{job=\"consul-server\"}[1m]) + increase(consul_catalog_deregister_count{job=\"consul-server\"}[1m]))) by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}