{
 "title": "Velero Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Backups Held",
   "type": "stat",
   "description": "The number of backups currently held.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(velero_backup_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Schedules",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "velero_backup_last_status{schedule!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "velero_backup_last_successful_timestamp{schedule!=\"\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "description": "The percentage of backups that have succeeded in the last 7 days.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total[$__range])) / sum(increase(velero_backup_attempt_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CSI Snapshot Success Rate",
   "type": "gauge",
   "description": "The percentage of CSI snapshots that succeeded in the last 7 days.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(velero_csi_snapshot_success_total)[$__range:]) / increase(sum(velero_csi_snapshot_attempt_total)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Count",
   "type": "timeseries",
   "description": "The number of backups by schedule.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(increase(velero_backup_success_total[$__rate_interval])) by(schedule))",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "round(sum(increase(velero_backup_failure_total[$__rate_interval])) by(schedule))",
     "legendFormat": "{{schedule}} - failure"
    }
   ]
  },
  {
   "title": "CSI Snapshot Count",
   "type": "timeseries",
   "description": "The number of CSI snapshots by schedule.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "round(increase(sum(velero_csi_snapshot_success_total) by(schedule)[$__rate_interval:]))",
     "legendFormat": "{{schedule}} - success"
    },
    {
     "expr": "round(increase(sum(velero_csi_snapshot_failure_total) by(schedule)[$__rate_interval:]))",
     "legendFormat": "{{schedule}} - failure"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sum(velero_backup_duration_seconds_sum) by(schedule)[$__rate_interval:]) / rate(sum(velero_backup_duration_seconds_count) by(schedule)[$__rate_interval:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "timeseries",
   "description": "The size of the most recent backup for each schedule.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(velero_backup_tarball_size_bytes) by(schedule)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Items",
   "type": "timeseries",
   "description": "The number of items in the last backup for each schedule.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(velero_backup_items_total) by(schedule) > 0",
     "legendFormat": "{{schedule}} - total"
    },
    {
     "expr": "sum(velero_backup_items_errors) by(schedule) > 0",
     "legendFormat": "{{schedule}} - errors"
    }
   ]
  }
 ]
}