---
- name: Install Slack webhook URL secret
  ansible.builtin.command: kubectl apply -f -
  args:
    stdin: "{{ alertmanager_config_slack_webhook_secret_definition | to_nice_yaml }}"
  vars:
    alertmanager_config_slack_webhook_secret_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ alertmanager_config_slack_webhook_secret_name }}"
        namespace: "{{ alertmanager_config_namespace }}"
        labels: "{{ alertmanager_config_labels }}"
      stringData: >-
        {{-
          { alertmanager_config_slack_webhook_secret_key: alertmanager_config_slack_webhook_url }
        }}
  register: kubectl_slack_webhook_url
  changed_when: kubectl_slack_webhook_url.stdout_lines | select('match', '(?!.*unchanged$)') | length > 0

- name: Install alertmanager configuration for Slack alerts
  ansible.builtin.command: kubectl apply -f -
  args:
    stdin: "{{ alertmanager_config_slack_definition | to_nice_yaml }}"
  vars:
    alertmanager_config_slack_definition:
      apiVersion: monitoring.coreos.com/v1alpha1
      kind: AlertmanagerConfig
      metadata:
        name: "{{ alertmanager_config_slack_name }}"
        namespace: "{{ alertmanager_config_namespace }}"
        labels: "{{ alertmanager_config_labels }}"
      spec: "{{ alertmanager_config_slack_spec }}"
  register: kubectl_alertmanager_slack
  changed_when: kubectl_alertmanager_slack.stdout_lines | select('match', '(?!.*unchanged$)') | length > 0
