---

- name: Install sealed secrets controller on target Kubernetes cluster
  kubernetes.core.helm:
    chart_ref: "{{ sealed_secrets_chart_name }}"
    chart_repo_url: "{{ sealed_secrets_chart_repo }}"
    chart_version: "{{ sealed_secrets_chart_version }}"
    release_namespace: "{{ sealed_secrets_release_namespace }}"
    release_name: "{{ sealed_secrets_release_name }}"
    release_values: "{{ sealed_secrets_release_values }}"
    atomic: true
    create_namespace: true
    wait: true
    wait_timeout: "{{ sealed_secrets_wait_timeout }}"
