---

# The namespace that AWX should be deployed into
# Azimuth needs to access AWX secrets, so put it in the azimuth namespace by default
awx_namespace: "{{ azimuth_release_namespace | default('azimuth') }}"

# The directory into which the AWX operator should be cloned
awx_operator_directory: /opt/awx-operator

# The name for the AWX instance
awx_name: awx

# Release name for the postgresql release
awx_postgresql_release_name: "{{ awx_name }}-postgresql"
# The name of the secret containing the postgresql passwords
awx_postgresql_auth_secret_name: "{{ awx_name }}-postgresql-auth"

# The database connection details for the postgresql database used by AWX
# If database host is not set, then a database is created using the Bitnami Helm chart
# The name of the secret containing the postgresql configuration for AWX
awx_postgresql_configuration_secret_name: "{{ awx_name }}-postgresql-configuration"

# The name of the secret containing the AWX trust bundle
awx_trust_bundle_secret_name: "{{ trust_bundle_configmap_name | default('awx-trust-bundle') }}"
