{
 "title": "Cloud Metrics",
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "flavors",
    "query": {
     "query": "label_values(openstack_free_capacity_by_flavor_total, flavor_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary Hypervisor Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Memory",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_hypervisor_placement_allocatable_capacity{resource=\"MEMORY_MB\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"MEMORY_MB\"})",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "sum(openstack_hypervisor_placement_allocated{resource=\"MEMORY_MB\"})",
     "legendFormat": "Allocated Memory"
    }
   ]
  },
  {
   "title": "Total Pinned CPU",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_hypervisor_placement_allocatable_capacity{resource=\"PCPU\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"PCPU\"})",
     "legendFormat": "Free PCPU"
    },
    {
     "expr": "sum(openstack_hypervisor_placement_allocated{resource=\"PCPU\"})",
     "legendFormat": "Allocated PCPU"
    }
   ]
  },
  {
   "title": "Total Non-Pinned CPU",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_hypervisor_placement_allocatable_capacity{resource=\"VCPU\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"VCPU\"})",
     "legendFormat": "Free VCPU"
    },
    {
     "expr": "sum(openstack_hypervisor_placement_allocated{resource=\"VCPU\"})",
     "legendFormat": "Allocated VCPU"
    }
   ]
  },
  {
   "title": "Total Local Disk",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_hypervisor_placement_allocatable_capacity{resource=\"DISK_GB\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"DISK_GB\"})",
     "legendFormat": "Free Local Disk"
    },
    {
     "expr": "sum(openstack_hypervisor_placement_allocated{resource=\"DISK_GB\"})",
     "legendFormat": "Allocated Local Disk"
    }
   ]
  },
  {
   "title": "Free Capacity by Flavor",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_free_capacity_by_flavor_total{}",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  { "title": "Project Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory Used by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(openstack_project_usage{placement_resource=\"MEMORY_MB\"}[30m])",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "PCPUs Used by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(openstack_project_usage{placement_resource=\"PCPU\"}[30m])",
     "legendFormat": "PCPU {{project_name}}"
    }
   ]
  },
  {
   "title": "VCPUs Used by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(openstack_project_usage{placement_resource=\"VCPU\"}[30m])",
     "legendFormat": "VCPU {{project_name}}"
    }
   ]
  },
  {
   "title": "Other resources by Project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(openstack_project_usage{placement_resource!~\"VCPU|PCPU|MEMORY_MB|DISK_GB\"}[30m])",
     "legendFormat": "{{project_name}} {{placement_resource}}"
    }
   ]
  },
  { "title": "Per Hypervisor Free Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Available Capacity for $flavors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg_over_time(openstack_free_capacity_hypervisor_by_flavor{flavor_name=~\"$flavors\"}[30m])",
     "legendFormat": "{{flavor_name}} on {{hypervisor}}"
    }
   ]
  },
  {
   "title": "Memory Free by Hypervisor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(openstack_hypervisor_placement_allocatable_capacity{resource=\"MEMORY_MB\"}[30m]) - on(hypervisor) avg_over_time(openstack_hypervisor_placement_allocated{resource=\"MEMORY_MB\"}[30m])",
     "legendFormat": "{{hypervisor}}"
    }
   ]
  }
 ]
}