{
 "title": "Tenant Metrics",
 "tags": [
  "capacity",
  "azimuth"
 ],
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "project_id", "label": "Project", "query": { "query": "openstack_project_usage" } }
  ]
 },
 "panels": [
  { "title": "Project Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_project_usage{project_id=~\"${project_id}\",placement_resource=\"MEMORY_MB\"}) by (placement_resource) / 1024",
     "legendFormat": "Memory in GB"
    },
    {
     "expr": "sum(openstack_project_usage{project_id=~\"${project_id}\",placement_resource!=\"MEMORY_MB\"}) by (placement_resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers by flavor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count(libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}) by (domain,flavor)) by (flavor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources per Project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(openstack_project_usage{project_id=~\"${project_id}\"}[30m:])) by (placement_resource)",
     "legendFormat": "{{placement_resource}}"
    }
   ]
  },
  {
   "title": "Project quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(openstack_project_quota{project_id=~\"${project_id}\"}[30m:])",
     "legendFormat": "{{project_name}}:{{quota_resource}}"
    }
   ]
  },
  {
   "title": "CPU utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(irate(libvirt_domain_vcpu_time_seconds_total{}[5m]) / ignoring(instance,vcpu) group_left(domain) libvirt_domain_info_virtual_cpus{}) by (domain) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}) by (project_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(libvirt_domain_memory_stats_used_percent{} * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}) by (project_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(libvirt_domain_block_stats_read_time_seconds_total{}[5m]) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}) by (project_name)",
     "legendFormat": "read: {{project_name}}"
    },
    {
     "expr": "avg(rate(libvirt_domain_block_stats_write_time_seconds_total{}[5m]) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"} * -1) by (project_name)",
     "legendFormat": " write: {{project_name}}"
    }
   ]
  },
  { "title": "Per Instance Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_vcpu_time_seconds_total{}[5m]) / ignoring(instance,vcpu) group_left(domain) libvirt_domain_info_virtual_cpus{}) by (domain) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}",
     "legendFormat": "{{instance_name}} : read {{target_device}}"
    },
    {
     "expr": "avg(rate(libvirt_domain_block_stats_write_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"} * -1) by (project_name)",
     "legendFormat": "{{instance_name}} : write {{target_device}}"
    }
   ]
  },
  {
   "title": "Network per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_bytes_total{}[5m]) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}",
     "legendFormat": "receive: {{project_name}} {{instance_name}} {{target_device}}"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_bytes_total{}[5m]) * on(domain) group_left(instance_name,project_name,project_uuid) libvirt_domain_info_meta{project_uuid=~\"${project_id}\"}",
     "legendFormat": " transmit: {{project_name}} {{instance_name}} {{target_device}}"
    }
   ]
  }
 ]
}