---

# The name of the database resource
pgo_database_name: "{{ undef(hint = 'pgo_database_name is required') }}"
# The namespace in which to create the database resource
pgo_database_namespace: "{{ undef(hint = 'pgo_database_namespace is required') }}"
# The Postgres version to use for the database
pgo_database_version: 14
# The storage class to use for the database volume
# If left blank, the default storage class will be used
pgo_database_data_volume_storage_class:
# The storage class to use for the backup volume
# By default, this is the same as the data volume
pgo_database_backup_volume_storage_class: "{{ pgo_database_data_volume_storage_class }}"
# The size of the data volume for the database
pgo_database_data_volume_size: 8Gi
# The size of the backup volume for the database
# By default, this is the same as the data volume
pgo_database_backup_volume_size: "{{ pgo_database_data_volume_size }}"
# The spec of the database resource
pgo_database_spec_defaults:
  postgresVersion: "{{ pgo_database_version }}"
  # TODO(mkjpryor)
  # Remove this when we move to Postgres 15
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.11-0
  # Enable the monitoring sidecar
  monitoring:
    pgmonitor:
      exporter: {}
  instances:
    - name: instance1
      dataVolumeClaimSpec: >-
        {{-
          {
            "accessModes": ["ReadWriteOnce"],
            "resources": {
              "requests": {
                "storage": pgo_database_data_volume_size,
              },
            },
          } |
            combine(
              { "storageClassName": pgo_database_data_volume_storage_class }
              if pgo_database_data_volume_storage_class
              else {}
            )
        }}
  backups:
    pgbackrest:
      # TODO(mkjpryor)
      # Remove this when we move to Postgres 15
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec: >-
              {{-
                {
                  "accessModes": ["ReadWriteOnce"],
                  "resources": {
                    "requests": {
                      "storage": pgo_database_backup_volume_size,
                    },
                  },
                } |
                  combine(
                    { "storageClassName": pgo_database_backup_volume_storage_class }
                    if pgo_database_backup_volume_storage_class
                    else {}
                  )
              }}
pgo_database_spec_overrides: {}
pgo_database_spec: >-
  {{-
    pgo_database_spec_defaults |
      combine(pgo_database_spec_overrides, recursive = True)
  }}

# The relabelings expected by the dashboards from https://github.com/CrunchyData/postgres-operator-examples
pgo_servicemonitor_relabelings:
  - sourceLabels:
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster
    targetLabel: cluster
    replacement: '$1'
  - sourceLabels:
      - namespace
      - cluster
    targetLabel: pg_cluster
    separator: ":"
    replacement: '$1$2'
  - sourceLabels:
      - __meta_kubernetes_pod_ip
    targetLabel: ip
    replacement: '$1'
  - sourceLabels:
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance
    targetLabel: deployment
    replacement: '$1'
    separator: ""
  - sourceLabels:
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role
    targetLabel: role
    replacement: '$1'
    separator: ""
