#####
# This playbook uses Terraform and Cluster API to provision infrastructure onto which Azimuth is deployed
#####


# Provision the node using Terraform
- hosts: terraform_provision
  roles:
    - stackhpc.azimuth_ops.infra
  vars:
    infra_ansible_groups: [k3s, azimuth_deploy]


# Configure the node as a K3S cluster
- hosts: k3s
  tasks:
    - include_role:
        name: stackhpc.azimuth_ops.community_images

    - block:
        - include_role:
            name: stackhpc.azimuth_ops.k3s

        - name: Get installed Kubernetes version
          command: k3s kubectl version --output json
          changed_when: false
          register: k3s_kubectl_version

        - name: Set kubectl version fact
          set_fact:
            kubectl_version: "{{ (k3s_kubectl_version.stdout | from_json).serverVersion.gitVersion.split('+') | first }}"

        - include_role:
            name: stackhpc.azimuth_ops.kubectl

        - include_role:
            name: stackhpc.azimuth_ops.helm

        - include_role:
            name: stackhpc.azimuth_ops.kustomize

        - name: Slurp kubeconfig file
          slurp:
            src: /etc/rancher/k3s/k3s.yaml
          register: k3s_kubeconfig
      become: yes

    - name: Ensure kube config directory exists
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Write kubeconfig file
      copy:
        content: "{{ k3s_kubeconfig.content | b64decode }}"
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: u=rwx,g=,o=

    # For a single node install, we put the monitoring and ingress controller on the K3S cluster
    - block:
        # Must be done before NGINX ingress so that the ServiceMonitor CRD exists
        - include_role:
            name: stackhpc.azimuth_ops.kube_prometheus_stack

        - include_role:
            name: stackhpc.azimuth_ops.ingress_nginx
          when: "ingress_controller_enabled | default(true)"
      when: install_mode == 'singlenode'

    # Configure the K3S cluster as a Cluster API management cluster when doing a HA installation
    - block:
        - include_role:
            name: stackhpc.azimuth_ops.certmanager
          vars:
            certmanager_monitoring_enabled: no
            certmanager_acmehttp01issuer_enabled: no

        - include_role:
            name: stackhpc.azimuth_ops.clusterapi

        - include_role:
            name: stackhpc.azimuth_ops.capi_cluster
          vars:
            capi_cluster_kubeconfig_path: "{{ ansible_env.HOME }}/kubeconfig-{{ capi_cluster_release_name }}.yaml"
      when: install_mode == 'ha'
