---
name: Lint

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: true
          persist-credentials: false

      - name: Run ansible-lint
        uses: ansible/ansible-lint@e98f9b38769d45cbe3c55a23b2eb25631babe7c4 # v25.4.0

      - name: Load super-linter configuration
        # Use grep inverse matching to exclude eventual comments in the .env file
        # because the GitHub Actions command to set environment variables doesn't
        # support comments.
        # yamllint disable-line rule:line-length
        # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' super-linter.env >> "$GITHUB_ENV"
        if: always()

      - name: Run super-linter
        uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
