---
name: Lint 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

permissions:
  contents: read
  packages: write
  # To report GitHub Actions status checks
  statuses: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    if: github.repository == 'azimuth-cloud/ansible-collection-azimuth-ops'

    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          submodules: true

      - name: Run ansible-lint
        run: exit 0
        #uses: ansible/ansible-lint@v25.4.0

      - name: Run super-linter
        # This is a workaround if the ansible-lint step fails
        if: always()
        #uses: super-linter/super-linter@v7.3.0
        run: exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_ANSIBLE: false

